package com.kenny.AllStarBattle;

public enum Gametype {
    //正常游戏关卡的Entity种类
    BUllet,ENEMY,PLAYER1,PLAYER2,CASEBLOCK,LUCKYBLOCK,STONEBLOCK,UNBREAKABLEWALL,WALL,Green,BORDER,PROPS,BOSS,CHICKEN,CHICKENENEMY, EGG,ENEMYEYE,SHARPEYE,PEOPLE
}
